# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
        - name: my-database
          image: atallah0/backend-final-4-app:latest
          ports:
            - containerPort: 3306
          env:
            - name: DB_HOST
              value: "bpjdtcusvfya081dups9-mysql.services.clever-cloud.com"
            - name: DB_USER
              value: "ue1nqowcpn0mvluj"
            - name: DB_PASSWORD
              value: "kiVFBrPl2fYHLBUt0eRR"
            - name: DB_NAME
              value: "bpjdtcusvfya081dups9"
            - name: JWT_SECRET
              value: "jwtS$12345er"
