version: '3.8'

services:
  # MySQL database service
  db:
    hostname: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=finalproject4db
      - LANG=C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - backend-final
    healthcheck:
      test: [ "CMD", "mysqladamin", "ping", "-h", "phpmyadmin" ]
      timeout: 40s
      retries: 10
      interval: 5s

  # phpMyAdmin service
  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=
    ports:
      - "8080:80"
    networks:
      - backend-final
    links:
      - db

networks:
  backend-final:
    driver: bridge
