version: '3.8'

services:
  # Node.js application service
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=finalproject4db
    networks:
      - backend-final
    depends_on:
      - db
      - phpmyadmin
    command: sh -c 'sleep 40 && npm start'
    links:
      - db
